### ISSUE TITLE
How to achieve PDF vertical sliding continuous reading？

### ISSUE THREAD

**Issue by Chittyo** [ArtifexSoftware/mupdf-android-viewer#16]
How to achieve PDF vertical sliding continuous reading？Please Help me, thanks!

**Comment by ccxvii** [comment]
This android viewer only supports a horizontal paging.

**Comment by Chittyo** [comment]
@ccxvii Can you help me? Give me some ideas. Thanks in advance !~

**Comment by Chittyo** [comment]
@ccxvii Thanks for your reply！By the way, do you have any plans to develop a PDF reading mode that supports continuous vertical scrolling in the future? Because the current mainstream PDF reading mode on the market is vertical continuous scrolling reading. I hope the mupdf library can support this reading mode. Looking forward to your reply, thank you ！

**Comment by robinwatts** [comment]
The library is certainly capable of supporting both continuous scrolling and vertical scrolling - indeed, different viewers out there already use it in those ways.

*This* viewer, however, is not designed to view more than 1 page at a time. Not doing continuous scrolling was a deliberate design choice.

Doing vertical, non-continuous scrolling might well be possible though. Indeed, in ReaderView.class there is a "HORIZONTAL_SCROLLING" constant that is currently set to true. Try setting it to false and see what happens?

**Comment by elementdavv** [comment]
Try the enhanced version of the viewer: [Chaka](https://github.com/elementdavv/chaka).
