### ISSUE TITLE
Opening files via content:// URI only works for PDF when mime type is not set

### ISSUE THREAD

**Issue by Unrud** [ArtifexSoftware/mupdf-android-viewer#3]
E.g. I can't open CBZ files from the file browser because it creates an Intent with a ``content://`` URI and the mime type ``*/*``. MuPDF Viewer tries to read the data as PDF which fails as expected.

The file name can be retrieved with [ContentResolver.query](https://developer.android.com/reference/android/content/ContentProvider#query(android.net.Uri,%20java.lang.String[],%20java.lang.String,%20java.lang.String[],%20java.lang.String)) and [OpenableColumns.DISPLAY_NAME](https://developer.android.com/reference/android/provider/OpenableColumns#DISPLAY_NAME). It could be used when the mime type is not set or generic.

**Comment by mohayou** [comment]
did you find any solution?

**Comment by Unrud** [comment]
Moved: https://bugs.ghostscript.com/show_bug.cgi?id=702421
